Fixed CCN Roadshow issues
openshift/openshift-cns-testdrive pull request #479
Opened 2019-12-18 17:16 UTC by pichuang

Before starting the CCN roadshow (12/19) in Taiwan, SA team found some issues below

1. Correct ServiceAccount name from `admin-cluster-admin` to `cluster-admin`
2. Fixed unknown user `system:serviceaccount:labguide:admin-user` to `kubeadmin`
3. Fixed one progress issue from section `template-quota-limits` to `networking`

2019-12-18 17:23 UTC, thoraxe requested changes
I think the other two changes are probably ok but I'm not sure what the `oc project default` switch is supposed to do.

2019-12-18 17:23 UTC, thoraxe commented on support/create-net-projects.sh
> +oc project default
What does this accomplish? The following commands are namespaced.

2019-12-18 17:31 UTC, pichuang commented on support/create-net-projects.sh
> +oc project default
If the attendee follow the lab guide, when they execute `oc delete project template-test`, then running the next section `OpenShift Networking and NetworkPolicy` and will see a error message `error: unable to process template namespaces "template-test" not found error: no objects passed to apply` after running `bash /opt/app-root/src/content/support/create-net-projects.sh`

2019-12-18 20:28 UTC, kaovilai commented on support/create-net-projects.sh
> +oc project default
could just add for `oc process`
```
-n netproj-a
-n netproj-b
```
[create-net-projects.sh#L13-L14](https://github.com/angry-tony/Future-exercises-support/blob/428ea1b1c406a2610bf3674425c074187ba90ffe/src/content/support/create-net-projects.sh#L13-L14)
?

2019-12-20 13:23 UTC, pichuang commented on support/create-net-projects.sh
> +oc project default
@angry-tony +1

2019-12-20 13:25 UTC, pichuang commented
Remove the patch 3

2020-01-03 14:53 UTC, techjw commented
Actually, based on the description, I think the Service Account command is supposed to use `dashboard-cluster-admin` since the prior command shows that you are using the dashboard-user service account.

2020-01-13 14:56 UTC, thoraxe commented
@techjw So is this PR accurate at this point or still needs changes?

2020-01-15 14:09 UTC, techjw commented
@thoraxe As the PR stands today, it would allow the lab users to get a valid output as opposed to an error about the incorrect Service Account. However, the intent of the checking the Service Account ClusterRoleBinding is to show that the user's Service Account has been granted cluster-admin.

2020-01-17 18:41 UTC, thoraxe commented
I don't think this PR is relevant anymore. We did a full scrub on OCP 4.2.

Can you peek at the dev branch and see?

2020-11-25 09:08 UTC, closed without merging