Adding Cluster Metering
openshift/openshift-cns-testdrive pull request #512
Opened 2020-01-23 19:35 UTC by chris-short

2020-01-23 21:52 UTC, thoraxe requested changes
One change requested

2020-01-23 21:52 UTC, thoraxe commented on workshop/workshop.yaml
> +  - cluster-metering
minor nit - since this is an "advanced" lab can we move it "below" clusterresourcequota?

2020-01-23 22:20 UTC, chris-short commented on workshop/workshop.yaml
> +  - cluster-metering
Done!

2020-01-29 16:19 UTC, thoraxe approved these changes

2020-01-29 16:19 UTC, merged